//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siredd_vf.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DataSIGWebEtab
    {
        public string CD_ETAB { get; set; }
        public string NOM_ETABL { get; set; }
        public string NOM_ETABA { get; set; }
        public string CD_NETAB { get; set; }
        public bool ensPrimG { get; set; }
        public bool ensPrimO { get; set; }
        public bool ensColG { get; set; }
        public bool ensColO { get; set; }
        public bool ensQualG { get; set; }
        public bool ensQualO { get; set; }
        public bool ensQualT { get; set; }
        public bool ensPrescoM { get; set; }
        public bool ensPrescoC { get; set; }
        public Nullable<bool> CPGE { get; set; }
        public Nullable<bool> BTS { get; set; }
        public string typeEtab { get; set; }
        public Nullable<System.DateTime> DO_ETAB { get; set; }
        public string NomCompletDirecteur { get; set; }
        public Nullable<int> NbEleves { get; set; }
        public Nullable<int> NbClasses { get; set; }
        public Nullable<int> NbSalles { get; set; }
        public Nullable<int> NbEnseignants { get; set; }
        public Nullable<int> NbPersoAdministratifs { get; set; }
        public Nullable<int> NbPersonnelServices { get; set; }
        public string ActiviteEtab { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    }
}
