//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siredd_vf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSIREDDEntities : DbContext
    {
        public DBSIREDDEntities()
            : base("name=DBSIREDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ACTUALITE> ACTUALITE { get; set; }
        public virtual DbSet<ASSAINISSEMENT> ASSAINISSEMENT { get; set; }
        public virtual DbSet<AXE_THEMATIQUE> AXE_THEMATIQUE { get; set; }
        public virtual DbSet<BARRAGE> BARRAGE { get; set; }
        public virtual DbSet<BASSIN> BASSIN { get; set; }
        public virtual DbSet<BASSIN_SIRE> BASSIN_SIRE { get; set; }
        public virtual DbSet<BASSIN_VERSANT> BASSIN_VERSANT { get; set; }
        public virtual DbSet<CAPTAGE_ONEE> CAPTAGE_ONEE { get; set; }
        public virtual DbSet<CARRIERE> CARRIERE { get; set; }
        public virtual DbSet<CATEGORIE_DOCUMENT> CATEGORIE_DOCUMENT { get; set; }
        public virtual DbSet<COMMUNES> COMMUNES { get; set; }
        public virtual DbSet<CONTENU_CMS> CONTENU_CMS { get; set; }
        public virtual DbSet<CONTENU_STAT_CMS> CONTENU_STAT_CMS { get; set; }
        public virtual DbSet<DECHARGE> DECHARGE { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENT { get; set; }
        public virtual DbSet<DOMAINE> DOMAINE { get; set; }
        public virtual DbSet<DOMAINE_STRUCTUREL> DOMAINE_STRUCTUREL { get; set; }
        public virtual DbSet<DONNEE_ET_INDICATEUR> DONNEE_ET_INDICATEUR { get; set; }
        public virtual DbSet<DONNEE_INDICATEUR> DONNEE_INDICATEUR { get; set; }
        public virtual DbSet<DOUAR> DOUAR { get; set; }
        public virtual DbSet<DROIT> DROIT { get; set; }
        public virtual DbSet<DROITS_AUTORISES> DROITS_AUTORISES { get; set; }
        public virtual DbSet<ETAT_AEP_CENTRE> ETAT_AEP_CENTRE { get; set; }
        public virtual DbSet<ETAT_ASSAINISSEMENT_CENTRE> ETAT_ASSAINISSEMENT_CENTRE { get; set; }
        public virtual DbSet<EVENEMENT> EVENEMENT { get; set; }
        public virtual DbSet<FORET> FORET { get; set; }
        public virtual DbSet<FORMAT_DOCUMENT> FORMAT_DOCUMENT { get; set; }
        public virtual DbSet<HUILERIE> HUILERIE { get; set; }
        public virtual DbSet<INDICATEURS_TBS> INDICATEURS_TBS { get; set; }
        public virtual DbSet<INONDATION> INONDATION { get; set; }
        public virtual DbSet<LIMITE_ABHL> LIMITE_ABHL { get; set; }
        public virtual DbSet<MARJA> MARJA { get; set; }
        public virtual DbSet<MEDIATHEQUE> MEDIATHEQUE { get; set; }
        public virtual DbSet<MER> MER { get; set; }
        public virtual DbSet<MESSAGE_CONTACT> MESSAGE_CONTACT { get; set; }
        public virtual DbSet<NAPPES> NAPPES { get; set; }
        public virtual DbSet<OBJECTIFDD> OBJECTIFDD { get; set; }
        public virtual DbSet<OCCUPATION_SOL> OCCUPATION_SOL { get; set; }
        public virtual DbSet<ORGANISATION> ORGANISATION { get; set; }
        public virtual DbSet<PEDOLOGIE> PEDOLOGIE { get; set; }
        public virtual DbSet<PERIMETRE_IRRIGUE> PERIMETRE_IRRIGUE { get; set; }
        public virtual DbSet<PLAGE> PLAGE { get; set; }
        public virtual DbSet<POINT_INONDABLE> POINT_INONDABLE { get; set; }
        public virtual DbSet<POINTS_REJET> POINTS_REJET { get; set; }
        public virtual DbSet<PORTEE> PORTEE { get; set; }
        public virtual DbSet<PROFIL> PROFIL { get; set; }
        public virtual DbSet<PROJETS_ET_ETUDES> PROJETS_ET_ETUDES { get; set; }
        public virtual DbSet<PROVINCES> PROVINCES { get; set; }
        public virtual DbSet<QUALITE_EAU_BAIGNADE> QUALITE_EAU_BAIGNADE { get; set; }
        public virtual DbSet<QUALITE_RESSOURCE_SOUTERRAINE> QUALITE_RESSOURCE_SOUTERRAINE { get; set; }
        public virtual DbSet<QUALITE_RESSOURCE_SUPERFICIELLE> QUALITE_RESSOURCE_SUPERFICIELLE { get; set; }
        public virtual DbSet<REGIONS> REGIONS { get; set; }
        public virtual DbSet<RESEAU_HYDROGRAPHIE> RESEAU_HYDROGRAPHIE { get; set; }
        public virtual DbSet<RESEAU_HYDROGRAPHIQUE> RESEAU_HYDROGRAPHIQUE { get; set; }
        public virtual DbSet<RESEAU_ROUTIER> RESEAU_ROUTIER { get; set; }
        public virtual DbSet<RESEAU_SUIVI_ABHL> RESEAU_SUIVI_ABHL { get; set; }
        public virtual DbSet<RESEAU_SUIVI_QUALITE_EAU> RESEAU_SUIVI_QUALITE_EAU { get; set; }
        public virtual DbSet<RESPONSABLE> RESPONSABLE { get; set; }
        public virtual DbSet<SECTEURS_PROJET> SECTEURS_PROJET { get; set; }
        public virtual DbSet<SIBE> SIBE { get; set; }
        public virtual DbSet<SISMITE_REGION> SISMITE_REGION { get; set; }
        public virtual DbSet<SITE_RAMSAR> SITE_RAMSAR { get; set; }
        public virtual DbSet<SLIDER> SLIDER { get; set; }
        public virtual DbSet<SOURCE> SOURCE { get; set; }
        public virtual DbSet<SOUS_AXE_THEMATIQUE> SOUS_AXE_THEMATIQUE { get; set; }
        public virtual DbSet<SOUS_OBJECTIFDD> SOUS_OBJECTIFDD { get; set; }
        public virtual DbSet<SOUS_THEME> SOUS_THEME { get; set; }
        public virtual DbSet<STATION_HYDROLOGIQUE> STATION_HYDROLOGIQUE { get; set; }
        public virtual DbSet<STATION_METEROLOGIQUE> STATION_METEROLOGIQUE { get; set; }
        public virtual DbSet<STATION_POMPAGE> STATION_POMPAGE { get; set; }
        public virtual DbSet<TERRAIN_AGRICOLE> TERRAIN_AGRICOLE { get; set; }
        public virtual DbSet<THEMATIQUETBS> THEMATIQUETBS { get; set; }
        public virtual DbSet<THEME> THEME { get; set; }
        public virtual DbSet<UNITE> UNITE { get; set; }
        public virtual DbSet<UTILISATEUR> UTILISATEUR { get; set; }
        public virtual DbSet<VALEURS> VALEURS { get; set; }
        public virtual DbSet<VILLES> VILLES { get; set; }
        public virtual DbSet<VOIE_FERREE> VOIE_FERREE { get; set; }
        public virtual DbSet<ZONE_HUMIDE> ZONE_HUMIDE { get; set; }
        public virtual DbSet<ZONE_INDUSTRIELLS> ZONE_INDUSTRIELLS { get; set; }
        public virtual DbSet<DETAIL_INDICATEUR> DETAIL_INDICATEUR { get; set; }
        public virtual DbSet<INDICATEUR_GRAPHE> INDICATEUR_GRAPHE { get; set; }
        public virtual DbSet<PORTEES_COMMUNES> PORTEES_COMMUNES { get; set; }
        public virtual DbSet<PORTEES_PROVINCES> PORTEES_PROVINCES { get; set; }
        public virtual DbSet<PORTEES_REGION> PORTEES_REGION { get; set; }
        public virtual DbSet<VALEURS_CARTE_PROVINCE> VALEURS_CARTE_PROVINCE { get; set; }
        public virtual DbSet<VALEURS_CARTE_PROVINCES> VALEURS_CARTE_PROVINCES { get; set; }
        public virtual DbSet<CAPTAGE_ONEP> CAPTAGE_ONEP { get; set; }
        public virtual DbSet<COURBE_NIVEAU> COURBE_NIVEAU { get; set; }
        public virtual DbSet<FOURNISSEUR> FOURNISSEUR { get; set; }
        public virtual DbSet<DemandeUTILISATEUR> DemandeUTILISATEUR { get; set; }
        public virtual DbSet<THEMATIQUETBS_CC> THEMATIQUETBS_CC { get; set; }
        public virtual DbSet<INDICATEURS_TBS_CC> INDICATEURS_TBS_CC { get; set; }
        public virtual DbSet<DataSIGWebEtab> DataSIGWebEtab { get; set; }
    }
}
